### ISSUE TITLE
[Week 2 - 3 Homework] upgrade your code to better

### ISSUE THREAD

**Issue by sahinsrhn** [amernoureddin/CS240#1]
Firstly,
You wrote the codes but also run the cells, update your notebook with showing the input codes and output answer(you can run code cells to show output answer) 

Secondly,
"Show the columns and then show the first 20 and last 30 rows of dataframe and lastly print a sentences that show the number of rows and columns in this dataframe. For example, "There are .. rows and .. columns""
For the second question above, Think about programatically, try to find number of columns and rows, then assign them into a variable and in your print statement use these variables. For example,
print("There are %s rows and %s columns" % (rowCount, columnCount) )

Thirdly,
"What is the average of the Pregnancies in lifetime (column that called "numpregs") of who is at maximum age(column taht called "agescrn") ? that you found in 3. question"

For the last question above do not write maximum age manually, think about programatically, you found the maximum age before so assign it to a variable and use that variable in your code to find the answer

Finally,
Well done you write good codes.

**Comment by amernureddin** [comment]
@sahinsrhn Thank you for your comment.

I cleared the outputs intentionally, to make the code prettier. but I executed them now...
and the rest of the points that you mentioned I updated them.
