### ISSUE TITLE
About Homework 2 

### ISSUE THREAD

**Issue by sahinsrhn** [amernoureddin/CS240#2]
Nice codes well done. i just want mention just a tiny thing that totincr shows total income's category and i gave the link what is the totincr so just when you create totincr's histogram x axis label actually that should be "income category" not the total income

**Comment by amernureddin** [comment]
@sahinsrhn Yes, I will address that one, thank you for your feedback.

**Comment by amernureddin** [comment]
@sahinsrhn I'm trying to find the function in the thinkplot that can change the x axis ticks in order to change the values to their actual label in the website, any hint?

**Comment by sahinsrhn** [comment]
@amernoureddin  Do not convert the values to its actual values in website because to do that you must change the your data in that column and that is waste of your time, I gave the website link to show you what are the values and what is the definition of them . what i meant previous comment is just the change x-axis label from "Total income" to "income category" that is inside of thinkplot.Config . Also change width for all histograms not just for 4. question's histogram

**Comment by amernureddin** [comment]
@sahinsrhn Updated.
